"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    Archive,
    FileText,
    Download,
    ExternalLink,
    Search,
    Calendar,
    Clock,
    Database,
    ChevronRight,
    Code,
    Activity,
    Folder
} from "lucide-react";
import { cn } from "@/lib/utils";

interface MissionArtifact {
    id: string;
    timestamp: number;
    has_result: boolean;
    objective?: string;
    is_multifile?: boolean;
}

export default function MissionArchive() {
    const [missions, setMissions] = useState<MissionArtifact[]>([]);
    const [loading, setLoading] = useState(true);
    const [selectedMission, setSelectedMission] = useState<string | null>(null);
    const [missionSource, setMissionSource] = useState<{
        content?: string;
        filename?: string;
        is_multifile?: boolean;
        file_map?: Record<string, string>;
    } | null>(null);
    const [activeFile, setActiveFile] = useState<string | null>(null);
    const [fetchingSource, setFetchingSource] = useState(false);
    const [searchQuery, setSearchQuery] = useState("");

    const API_BASE_URL = process.env.NEXT_PUBLIC_PLATFORM_API_URL || "http://localhost:8000";

    useEffect(() => {
        fetchMissions();
    }, []);

    const fetchMissions = async () => {
        setLoading(true);
        try {
            const res = await fetch(`${API_BASE_URL}/missions`);
            const data = await res.json();
            setMissions(data);
        } catch (e) {
            console.error("Failed to fetch missions", e);
        } finally {
            setLoading(false);
        }
    };

    const handleViewSource = async (id: string) => {
        if (selectedMission === id) {
            setSelectedMission(null);
            setMissionSource(null);
            setActiveFile(null);
            return;
        }

        setSelectedMission(id);
        setFetchingSource(true);
        try {
            const res = await fetch(`${API_BASE_URL}/missions/${id}/source`);
            const data = await res.json();
            setMissionSource(data);

            if (data.is_multifile && data.file_map) {
                const files = Object.keys(data.file_map);
                if (files.length > 0) setActiveFile(files[0]);
            }
        } catch (e) {
            console.error("Failed to fetch mission source", e);
        } finally {
            setFetchingSource(false);
        }
    };

    const handleExportZip = async (id: string) => {
        try {
            const res = await fetch(`${API_BASE_URL}/missions/${id}/export`);
            const blob = await res.json(); // Wait, it's a file response
            // We should use window.open or a direct link for binary responses
            window.open(`${API_BASE_URL}/missions/${id}/export`, "_blank");
        } catch (e) {
            console.error("Failed to export ZIP", e);
        }
    };

    const filteredMissions = missions.filter(m =>
        m.id.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="min-h-screen p-6 md:p-12 max-w-7xl mx-auto flex flex-col gap-8">
            {/* Header */}
            <header className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div>
                    <h1 className="text-4xl font-bold tracking-tight text-white mb-2 uppercase">Mission <span className="text-primary tracking-[0.3em] font-light ml-2">Archive</span></h1>
                    <p className="text-muted leading-relaxed max-w-xl text-sm">
                        Browse, inspect, and retrieve tactical artifacts generated by the Ascension Swarm. Your codebase history is persisted in the sovereign sandbox.
                    </p>
                </div>

                <div className="relative group">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted/50 group-focus-within:text-primary transition-colors" size={16} />
                    <input
                        type="text"
                        placeholder="Search Mission ID..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="bg-white/[0.03] border border-white/10 rounded-full pl-12 pr-6 py-3 text-sm focus:outline-none focus:border-primary/40 focus:bg-white/[0.05] transition-all w-full md:w-64 text-white"
                    />
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Mission List */}
                <div className={cn("transition-all duration-500", selectedMission ? "lg:col-span-5" : "lg:col-span-12")}>
                    <div className="glass-card border border-white/5 bg-white/[0.01] flex flex-col overflow-hidden">
                        <div className="p-4 border-b border-white/5 bg-white/[0.02] flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <Database size={14} className="text-primary" />
                                <span className="text-[10px] font-mono text-white uppercase tracking-widest opacity-70">Sovereign Artifacts</span>
                            </div>
                            <span className="text-[10px] font-mono text-muted uppercase tracking-widest">{filteredMissions.length} Missions Found</span>
                        </div>

                        <div className="max-h-[700px] overflow-y-auto scrollbar-hide">
                            {loading ? (
                                <div className="p-12 flex flex-col items-center justify-center gap-4 text-muted">
                                    <Activity className="animate-pulse text-primary" />
                                    <span className="text-xs font-mono uppercase tracking-widest">Scanning Sandbox...</span>
                                </div>
                            ) : filteredMissions.length === 0 ? (
                                <div className="p-12 text-center text-muted">
                                    <Archive className="mx-auto mb-4 opacity-10" size={48} />
                                    <p className="text-sm">No tactical artifacts found in the sandbox.</p>
                                </div>
                            ) : (
                                <div className="divide-y divide-white/5">
                                    {filteredMissions.map((mission) => (
                                        <button
                                            key={mission.id}
                                            onClick={() => handleViewSource(mission.id)}
                                            className={cn(
                                                "w-full text-left p-5 flex items-center gap-6 transition-all group relative overflow-hidden",
                                                selectedMission === mission.id ? "bg-primary/5" : "hover:bg-white/[0.02]"
                                            )}
                                        >
                                            {selectedMission === mission.id && (
                                                <motion.div layoutId="active-indicator" className="absolute left-0 top-0 bottom-0 w-1 bg-primary shadow-[0_0_15px_rgba(0,229,255,1)]" />
                                            )}

                                            <div className={cn(
                                                "w-12 h-12 rounded-xl flex items-center justify-center border transition-all",
                                                selectedMission === mission.id ? "bg-primary/20 border-primary/30" : "bg-white/[0.03] border-white/5 group-hover:border-primary/20"
                                            )}>
                                                <Folder className={cn("w-5 h-5", selectedMission === mission.id ? "text-primary" : "text-muted group-hover:text-primary/70")} />
                                            </div>

                                            <div className="flex-1 min-w-0">
                                                <div className="flex items-center gap-3 mb-1">
                                                    <span className="font-mono text-sm font-bold text-white uppercase tracking-tight">Mission_{mission.id}</span>
                                                    {mission.has_result && <span className="text-[8px] bg-green-500/10 text-green-400 border border-green-500/20 px-2 py-0.5 rounded-full font-mono uppercase">Code Ready</span>}
                                                </div>
                                                <div className="flex items-center gap-4 text-[10px] text-muted font-mono uppercase tracking-wider opacity-60">
                                                    <div className="flex items-center gap-1">
                                                        <Calendar size={10} />
                                                        {new Date(mission.timestamp * 1000).toLocaleDateString()}
                                                    </div>
                                                    <div className="flex items-center gap-1">
                                                        <Clock size={10} />
                                                        {new Date(mission.timestamp * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                                    </div>
                                                </div>
                                            </div>

                                            <ChevronRight className={cn("transition-all text-muted/20 group-hover:text-primary/50", selectedMission === mission.id && "rotate-90 text-primary")} size={16} />
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Source Preview */}
                <AnimatePresence>
                    {selectedMission && (
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: 20 }}
                            className="lg:col-span-7 flex flex-col gap-4"
                        >
                            <div className="glass-card border border-white/10 bg-black/40 flex flex-col h-[700px] overflow-hidden">
                                <div className="p-4 border-b border-white/10 bg-white/[0.04] flex items-center justify-between">
                                    <div className="flex items-center gap-3">
                                        <Code className="text-primary w-4 h-4" />
                                        <span className="text-xs font-mono text-white lowercase tracking-tight">
                                            {fetchingSource ? "Retrieving source..." : missionSource?.filename || "source.code"}
                                        </span>
                                    </div>

                                    <div className="flex items-center gap-2">
                                        <button
                                            onClick={() => handleExportZip(selectedMission)}
                                            className="p-2 hover:bg-white/10 rounded-lg text-muted hover:text-white transition-all flex items-center gap-2 border border-white/5 active:scale-95"
                                            title="Export ZIP Bundle"
                                        >
                                            <Download size={14} className="text-primary" />
                                            <span className="text-[10px] font-mono uppercase tracking-widest hidden md:inline">Export ZIP</span>
                                        </button>

                                        {!missionSource?.is_multifile && (
                                            <button
                                                onClick={() => {
                                                    const content = missionSource?.content;
                                                    const filename = missionSource?.filename;
                                                    if (content && filename) {
                                                        const blob = new Blob([content], { type: "text/plain" });
                                                        const url = URL.createObjectURL(blob);
                                                        const a = document.createElement("a");
                                                        a.href = url;
                                                        a.download = filename;
                                                        a.click();
                                                    }
                                                }}
                                                className="p-2 hover:bg-white/10 rounded-lg text-muted hover:text-white transition-all flex items-center gap-2"
                                                title="Download Raw File"
                                            >
                                                <FileText size={14} />
                                            </button>
                                        )}
                                    </div>
                                </div>

                                <div className="flex-1 flex overflow-hidden">
                                    {/* Multi-file sidebar */}
                                    {missionSource?.is_multifile && missionSource.file_map && (
                                        <div className="w-48 border-r border-white/5 bg-black/20 overflow-y-auto p-2 flex flex-col gap-1">
                                            <div className="px-3 py-2 text-[9px] font-mono text-muted uppercase tracking-widest opacity-40">Filesystem</div>
                                            {Object.keys(missionSource.file_map).map(path => (
                                                <button
                                                    key={path}
                                                    onClick={() => setActiveFile(path)}
                                                    className={cn(
                                                        "px-3 py-2 text-left text-[11px] font-mono rounded transition-all truncate",
                                                        activeFile === path ? "bg-primary/20 text-primary" : "text-muted hover:text-white hover:bg-white/5"
                                                    )}
                                                >
                                                    {path.split('/').pop()}
                                                </button>
                                            ))}
                                        </div>
                                    )}

                                    <div className="flex-1 overflow-auto p-6 scrollbar-hide">
                                        {fetchingSource ? (
                                            <div className="h-full flex flex-col items-center justify-center gap-4 text-muted/30">
                                                <Activity className="animate-spin text-primary/30" />
                                                <span className="text-[10px] font-mono uppercase tracking-widest">Decrypting Sandbox Asset...</span>
                                            </div>
                                        ) : (
                                            <pre className="text-sm font-mono text-white/90 leading-relaxed selection:bg-primary/30">
                                                <code>
                                                    {missionSource?.is_multifile
                                                        ? (activeFile ? missionSource.file_map?.[activeFile] : "Select a file to view")
                                                        : (missionSource?.content || "// No Tactical Output Detected")}
                                                </code>
                                            </pre>
                                        )}
                                    </div>
                                </div>

                                <div className="p-3 border-t border-white/5 bg-black/40 flex items-center justify-between px-6">
                                    <div className="flex items-center gap-3">
                                        <div className="flex items-center gap-2 text-[9px] font-mono text-muted uppercase tracking-widest opacity-50">
                                            <FileText size={10} />
                                            ID: {selectedMission}
                                        </div>
                                        {missionSource?.is_multifile && (
                                            <div className="text-[9px] font-mono text-primary/60 uppercase tracking-widest px-2 py-0.5 border border-primary/20 rounded-full">
                                                Multi-File Project
                                            </div>
                                        )}
                                    </div>
                                    <div className="flex items-center gap-2 text-[9px] font-mono text-primary uppercase tracking-[0.2em]">
                                        Secure Labs Storage
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
