from fastapi import APIRouter, Header, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional
from api.integrations.github import GitHubService
from api.integrations.clerk import ClerkService
from api.usage_db import SessionLocal, SwarmMission, AuditLog
from utils.logger import logger
import json
import datetime

router = APIRouter(prefix="/v1/integrations/github", tags=["GitHub Integration"])

class PROrchestrationRequest(BaseModel):
    mission_id: str
    repo_name: str # e.g. "username/repo"
    github_token: Optional[str] = None # Now optional
    branch_name: Optional[str] = None
    title: Optional[str] = None

@router.post("/deploy")
async def deploy_to_github(
    payload: PROrchestrationRequest,
    x_clerk_user_id: str = Header(...)
):
    """
    Deploys a swarm mission's code directly to a GitHub repository as a PR.
    """
    with SessionLocal() as db:
        # 1. Fetch Mission
        mission = db.query(SwarmMission).filter(SwarmMission.id == payload.mission_id, SwarmMission.user_id == x_clerk_user_id).first()
        if not mission:
            raise HTTPException(status_code=404, detail="Mission artifact not found or unauthorized.")

        # 2. Extract File Map
        file_map = {}
        if mission.is_multifile and mission.file_map:
            try:
                file_map = json.loads(mission.file_map)
            except json.JSONDecodeError:
                logger.error(f"GITHUB: Failed to parse file_map for mission {mission.id}")
                raise HTTPException(status_code=500, detail="Corrupt mission file map.")
        else:
            # Single file fallback
            file_map = {mission.filename or "result.txt": mission.source_code}

        # 3. Initialize Token
        github_token = payload.github_token
        
        if not github_token:
            clerk = ClerkService()
            github_token = await clerk.get_github_token(x_clerk_user_id)
            
        if not github_token:
            raise HTTPException(
                status_code=401, 
                detail="GitHub authentication failed. Please provide a token or link your GitHub account via settings."
            )

        # 4. Initialize Service
        gh = GitHubService(github_token)
        
        branch = payload.branch_name or f"swarm-mission-{mission.id[:8]}"
        title = payload.title or f"Swarm Update: {mission.objective[:50]}"
        body = (
            f"Automated implementation generated by Astraeus Intelligence Platform.\n\n"
            f"**Objective:** {mission.objective}\n\n"
            f"**Files:** {len(file_map)}\n"
            f"**Generated:** {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n"
            f"**Platform:** v5.2.1"
        )

        # 5. Execute PR Flow
        pr_url = await gh.create_pull_request(
            repo_full_name=payload.repo_name,
            file_map=file_map,
            branch_name=branch,
            title=title,
            body=body
        )

        if not pr_url:
            raise HTTPException(status_code=502, detail="GitHub API failure. Check token scopes or repo permissions.")

        logger.info(f"GITHUB: PR deployed for mission {mission.id[:8]} → {payload.repo_name} ({len(file_map)} files)")
        with SessionLocal() as db:
            db.add(AuditLog(user_id=x_clerk_user_id, action="GITHUB_PR_DEPLOYED", metadata_json=f"Repo: {payload.repo_name}, Mission: {mission.id[:8]}"))
            db.commit()

        return {
            "status": "success",
            "pr_url": pr_url,
            "files_deployed": len(file_map),
            "branch": branch
        }
